
name: CI
on:
  pull_request:
    branches: [ "Develop", "Staging", "main", "Master" ]
  push:
    branches:
      - "Develop"
      - "Staging"
      - "main"
      - "Master"
      - "feature/**"
      - "WIP-*"
      - "bug-fix-*"
      - "hot-fix-*"
permissions:
  contents: read
  security-events: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: API - install, test, build
        working-directory: BackEnd/Node/api
        run: |
          npm ci
          npm test
      - name: Portal - install, test, build
        working-directory: FrontEnd/React/portal
        run: |
          npm ci
          npm test
          npm run build

  trivy-sca:
    name: Trivy SCA
    runs-on: ubuntu-latest
    needs: [ build-test ]
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scanners: 'vuln'
          format: 'sarif'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git --redact --report-format sarif --report-path gitleaks.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: gitleaks.sarif }

  codeql:
    name: CodeQL (warning-only)
    runs-on: ubuntu-latest
    needs: [ build-test ]
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with: { languages: 'javascript-typescript' }
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3
    continue-on-error: true

  dep-review:
    name: Dependency Review
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with: { fail-on-severity: high }

  jacoco:
    name: JaCoCo (informativo)
    runs-on: ubuntu-latest
    steps:
      - run: echo "No aplica para Node/React; placeholder informativo."
    continue-on-error: true
